Added explosion effect when the vehicle collides with the bullseye target
afourneaux/rocket-racing-476 pull request #29
Opened 2022-04-04 20:21 UTC by Aether700

Created an explosion prefab which spawns in whenever a vehicle collides with the bullseye target at the end of the race.

To test go to the TrackTest scene and look at the vehicles as they collide with the bullseye at the end of the race track

2022-04-05 23:59 UTC, NathanZiri requested changes
The explosion looks good but was the track removed in the canyon race track?

2022-04-06 01:37 UTC, Aether700 commented
> The explosion looks good but was the track removed in the canyon race track?

No it wasn't, this branch is based off of main which never had the canyon track in the first place hence why it is not on this branch

2022-04-06 01:50 UTC, NathanZiri commented
Looks good then

2022-04-06 01:51 UTC, NathanZiri approved these changes

2022-04-06 01:55 UTC, merged